Repository nclgbd/Little-Amber, pull requests merged in 2021-07, with the labels that each got.

#29 Removed workflow, it's broken and I don't want the emails anymore. Added project board functionality.
  .github/workflows/aws.yml
  scripts/main.py
Labels: enhancement

#32 Sqlite
  db.db
  scripts/db/commands.py
  scripts/db/db.db
  scripts/db/setup.py
  scripts/main.py
Labels: help wanted

#43 Added back the raccoon pictures
  scripts/main.py
Labels: rework

#44 Changed !bookclub command to operator using subgroups
  scripts/main.py
Labels: automerge, rework

#47 setup-config
  .github/workflows/launch-bot.yml
Labels: automerge

#49 setup-config
  .github/workflows/launch-bot.yml
Labels: automerge

#52 setup-config
  .github/workflows/launch-bot.yml
  deploy_amber.sh
Labels: rework

#53 Setup config
  .github/workflows/launch-bot.yml
  quick_push.bat
Labels: rework

#55 setup-config
  .github/workflows/launch-bot.yml
Labels: automerge

#56 Put the name param in the wrong place
  .github/workflows/launch-bot.yml
Labels: automerge, rework

#57 Commented out setup-config
  .github/workflows/launch-bot.yml
Labels: automerge, rework
